---
- name: build-image
  hosts: docker, localhost
  become: yes
  become_method: sudo
  tasks:
    - name: build image
      shell: docker build -t image /home/seanghorn/opt/project-app/.
    - name: tag image
      shell: docker tag image seanghorn/image
    - name: log in
      shell: docker login --username seanghorn --password seanghorn
    - name: push image
      shell: docker push seanghorn/image
